services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    networks: [flink-net]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    networks: [flink-net]
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  jobmanager:
    image: flink:1.17
    networks: [flink-net]
    ports:
      - "8081:8081"
    command: jobmanager
    depends_on: [kafka]
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./jobs:/opt/flink/usrlib

  taskmanager:
    image: flink:1.17
    networks: [flink-net]
    depends_on: [jobmanager]
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  postgres:
    image: postgres:15
    networks: [flink-net]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: sentiment_db
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  flink-net:

volumes:
  kafka-data:
  pg-data:
